### ISSUE TITLE
After Clicking on Choose Color there should be a way for canceling

### ISSUE THREAD

**Issue by snowparrot** [RonnyDo/ColorPicker#27]
After I clicked on "Choose Color" - Button there is no way of canceling it ( Or it isn't written anywhere).

**Comment by RonnyDo** [comment]
Yes, it can be cancelled by pressing ESC. Since It isn't documented anywhere this is a valid issue.
I'll probably gonna document it in the about-section, once there is one. I won't like to display a message like "press ESC to cancel" or somewhat, because native apps, like screenshot, display it neither. Thanks for the report!

**Comment by snowparrot** [comment]
@RonnyDo I would like to add Right Click for Canceling.

**Comment by RonnyDo** [comment]
@snowparrot could you may provide an example where the right button is used to cancel a dialog. That wouldn't be intuitive for most of the users IMHO. But thanks anyway!

**Comment by snowparrot** [comment]
I suppose in Computer Games. It was the first reaction in my mind to cancel this kind of interaction.

**Comment by RonnyDo** [comment]
Since I can't see that it would distract the usability somehow and it's actually quite simple to implement, I'll going to implement it. Thanks for sharing the idea!
