### ISSUE TITLE
Easier way on working pixelwise

### ISSUE THREAD

**Issue by snowparrot** [RonnyDo/ColorPicker#36]
Current situation:

It is very hard to go "one Pixel left or right". This is a problem in complex pictures where to hit the exact pixel.

Situation: Find a way to just push the mouse for one pixel in a direction.

Possible solution: In color-picking mode if you hit the arrow keys mouse just goes one element in the direction (arrow left -> mouse goes one pixel left etc.)

**Comment by Janiczek** [comment]
I have a similar (same?) problem.The magnified view updates with much slower framerate than my mouse. I don't know whether that's because of my display being 4K (more stuff to process? bigger image to magnify?) or something else.

Also, moving one pixel on a touchpad is really hard :) But tools like Shutter do somehow make the mouse movement result in less-than-pixel cursor movement. Maybe that could be an inspiration? :)

**Comment by RonnyDo** [comment]
Hi @Janiczek, your problem seems more like issue #29 I guess. Unfortunately there doesn‘t seem to be a solution for this. 

Maybe you could drop your System configuration for debugging purposes. It apparently happens often to owners of AMD graphic cards. 4K displays could be a reason as well because the underlying system functions may not fast enough to buffer magnifier to highlighted area. I can‘t really work on this issue because I‘m lacking of the necessary hardware :-/
