### ISSUE TITLE
Works for Arch but not for Debian?

### ISSUE THREAD

**Issue by koesherbacon** [RonnyDo/ColorPicker#48]
Hey there.  I was testing a LiveUSB of an Arch-based distro and happened upon this amazing ColorPicker package in the AUR (https://aur.archlinux.org/packages/color-picker/).  It installed and worked perfectly and is the best color identifier package I've ever used.  When I switched back to my Debian-based distro installed on my laptop I attempted to install the package once again.  This time, however, nothing I did worked.  I tried downloading the .deb package, git cloning and building from source, and even adding ElementaryOS's PPA in order to install its dependencies.  Unfortunately none of these options worked and I still cannot get it to install.  Is there anything you can tell me which might help me out?  Might it be possible to convert the ColorPicker to another version that does not require Granite (the dependency that seems to be the most problematic).

Thanks for any info you can give me!  Happy holidays!

**Comment by orzechow** [comment]
Same here on an Ubuntu based system...

**Comment by RonnyDo** [comment]
Hi guys, I just released a new version of the app https://github.com/RonnyDo/ColorPicker/releases :-)
I tested it on Ubuntu 18.04 and it worked as well! Try the following steps:
```
git clone https://github.com/RonnyDo/ColorPicker.git
sudo apt install valac libgranite-dev
cd ColorPicker/
sudo chmod +x dev-build.sh
./dev-build.sh
```
That's it! Looks a little bit different from the elementaryos style but never mind

**Comment by orzechow** [comment]
Alright, I guess we both meant that installation from the .deb file does not work (neither 1.0.0, 1.0.1, nor 1.0.2).

Building and installing from source works on my Ubuntu 16.04 based system, thanks for that!
Though I also had to install `meson`.

It's a pity that your latest releases do not contain a .deb file anymore. I guess many people are put off when asked to build from source (and uninstalling is more cumbersome then).

**Comment by RonnyDo** [comment]
I don't have much knowledge about this build-system stuff. But since the app is made for elemtaryos, I don't have to care about that, because I can release my code in some simple steps:
1. Create new release on Github
2. Go to developer.elementary.io and let their system check your app. if everything worked fine, they build the app for me and release it in their appstore.

What I want to say is, that I never had the goal to release for a different system than elemntaryOS. The .deb file which was there until ColorPicker Release 1.0.2 was more or less by accident, because their build system put it there. However it seems they have changed it afterwards.

BUUUUT I just figured out, you can download the latest .deb file from: http://packages.elementary.io/appcenter/pool/main/c/com.github.ronnydo.colorpicker/ :-) Enjoy!

**Comment by orzechow** [comment]
Thanks, those deb packages from the appcenter work out of the box :)  
In this case, you should update your readme about the deb files, it still links to the github releases page.

Another option that I tested successfully now is to install the AppCenter on Ubuntu, see https://askubuntu.com/a/955229
